create table WN16
(DN int unsigned not null primary key,
钢管外径A1A char(5) not null,
钢管外径A1B char(5) not null,
法兰外径D char(5) not null,
螺栓孔中心圆直径K char(5) not null,
螺栓孔直径L char(5) not null,
螺栓孔数量n char(5) not null,
螺栓Th char(5) not null,
法兰厚度C char(5) not null,
法兰颈NA char(5) not null,
法兰颈NB char(5) not null,
法兰颈S char(5) not null,
法兰颈H1 char(5) not null,
法兰颈R char(5) not null,
法兰高度H char(5) not null);
